#!/bin/bash

CMD="${0##*/}"
LOG="$HOME/.breaker.log"
touch "${LOG}"

case "${CMD}" in
	smoke)
	  export HANDLER="[SMOKE]"
	  ;;
	lunch)
	  export HANDLER="[LUNCH]"
	  ;;
	*)
	  export HANDLER="[BREAK]"
esac

if [ "${1}" ]; then {
	case "${1}" in
	summary)
	  echo "Breaker Summary; last 10"
	  tail -10 "${LOG}"
	  ;;
	*)
	  echo "Usage: [smoke|lunch] [summary]"
	  ;;
	esac
exit 0
}; fi

DATE_HOUR=$(date +"%H")
LAST_HOUR=$(tail -1 ~/.breaker.log |sed -e "s/.*ending on.*\([0-9][0-9]\):\([0-9][0-9]:[0-9][0-9]\).*/\1/")
if [ "${DATE_HOUR}" == "${LAST_HOUR}" ]; then {
	echo "[2J[1;31mYou've already taken a break this hour!  Get back to work.[0m"
	tail -1 "${LOG}"
	exit
}; fi


echo "Hit that break!!! Press any key when you get back."
DATE="$(date)"
open -a /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app&
TIME=`(time read -n 1) 2>&1 | grep real|cut -d ' ' -f2`
echo "${HANDLER} ${TIME} starting on ${DATE} and ending on $(date)" >> "${LOG}"
echo "Welcome back!"
tail -1 "${LOG}"
